name: Lighthouse CI tests
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup Python Installation
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install wheel==0.35.0
      - name: Install Third Party Dependencies
        run: python -m scripts.install_third_party_libs
      - name: Run lighthouse checks
        run: python -m scripts.run_lighthouse_tests
